# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Verilog/Math_Project/U201514658/preject/preject.cache/wt [current_project]
set_property parent.project_path F:/Verilog/Math_Project/U201514658/preject/preject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  F:/Verilog/Math_Project/U201514658/preject/preject.srcs/sources_1/new/counter.v
  F:/Verilog/Math_Project/U201514658/preject/preject.srcs/sources_1/new/edge.v
  F:/Verilog/Math_Project/U201514658/preject/preject.srcs/sources_1/new/divider_M.v
  F:/Verilog/Math_Project/U201514658/preject/preject.srcs/sources_1/new/divider.v
  F:/Verilog/Math_Project/U201514658/preject/preject.srcs/sources_1/new/xianshi.v
  F:/Verilog/Math_Project/U201514658/preject/preject.srcs/sources_1/new/fuzhi.v
  F:/Verilog/Math_Project/U201514658/preject/preject.srcs/sources_1/new/FSM_main.v
  F:/Verilog/Math_Project/U201514658/preject/preject.srcs/sources_1/new/pattern_choose.v
  F:/Verilog/Math_Project/U201514658/preject/preject.srcs/sources_1/new/Main.v
}
read_xdc F:/Verilog/Math_Project/U201514658/preject/preject.srcs/constrs_1/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files F:/Verilog/Math_Project/U201514658/preject/preject.srcs/constrs_1/Nexys4DDR_Master.xdc]

synth_design -top Main -part xc7a100tcsg324-1
write_checkpoint -noxdef Main.dcp
catch { report_utilization -file Main_utilization_synth.rpt -pb Main_utilization_synth.pb }
